### ISSUE TITLE
BUG: the code used to verify a just written firmware doesn't work properly

### ISSUE THREAD

**Issue by gianogli** [setarcos/ch341prog#11]
The code added with this [commit](https://github.com/setarcos/ch341prog/commit/da404b46a5fb04231144b65fabbebc273d40f2cd) doesn't find any error even if the firmware has been corrupted during the write process.
The issue is here:
```
int ch1, ch2;
ch1 = getc(fp);
ch2 = getc(test_file);

while ((ch1 != EOF) && (ch2 != EOF) && (ch1 == ch2)) {
    ch1 = getc(fp);
    ch2 = getc(test_file);
}
```
The "start of file" pointers of `FILE *` variables are not reset before start the test. `ch1` and `ch2` are always equal to `EOF` so the test exit always without find any errors.

To solve the BUG you have to modify the code in this way:

```
fseek(fp, 0, SEEK_SET);
fseek(test_file, 0, SEEK_SET);

int ch1, ch2;
ch1 = getc(fp);
ch2 = getc(test_file);

while ((ch1 != EOF) && (ch2 != EOF) && (ch1 == ch2)) {
    ch1 = getc(fp);
    ch2 = getc(test_file);
}
```
You have also to modify the mode used to open the `test_filename` file from:

`test_file = fopen(test_filename, "wb");`

to:

`test_file = fopen(test_filename, "w+b");`

In this way the verification of a written firmware works fine! ;-)

Could you add this patch to your code?
Thanks...
    Gianluca

**Comment by dronov** [comment]
@gianogli Thank you! I will make a new PR to solve this.

**Comment by dronov** [comment]
Hey @setarcos and @gianogli 
PR was merged, I think this issue could be closed.
