### ISSUE TITLE
ETA goes negative

### ISSUE THREAD

**Issue by naf419** [setarcos/ch341prog#15]
When writing large flash chips, the ETA displayed in verbose mode goes negative.

The problem is integer overflow when calculating the ETA time:
`(int) ( (dur*size*1.0)/done-dur))`

When dur*size > 2^31 (such as size = 8MB and dur > 256s), this overflows signed integers before being cast to double, so the ETAs for the second half of the write are negative nonsense.

(i get bored waiting on the flash to write)

**Comment by dronov** [comment]
:+1:
