### ISSUE TITLE
Incopatible programmer

### ISSUE THREAD

**Issue by hpeterka** [setarcos/ch341prog#2]
Hello. I have CH341 programmer from ebay, but it not work with this software.

`$ lsusb`
`Bus 001 Device 005: ID 1a86:5523 QinHeng Electronics CH341 in serial mode, usb to serial port converter`

This software work only with 1a86:5512. It can be modified to work with 1a86:5523?

My programmer is bought [http://www.ebay.com/itm/201364328713](here)

Many thanks!

**Comment by setarcos** [comment]
Hi,

I wrote this software by probing the usb bus and guessing from the datasheet. Since I have only 1a86:5512 device at hand, it's probably the only chip I can support.

**Comment by hpeterka** [comment]
Ok, thanks for inforamation.

**Comment by lorf** [comment]
@hpeterka 0x5523 is the PID of CH341 in UART mode, 0x5512 is the PID of CH341 in MEM mode. You just need to switch your programmer to MEM mode, this can probably be done with a jumper. See the [CH341 datasheet](http://www.oomipood.ee/drivers/ch341a_programmer/CH341_chip.pdf), page 7.
