### ISSUE TITLE
compatibility with 24c02

### ISSUE THREAD

**Issue by paolo-caroni** [setarcos/ch341prog#6]
Hello,
I have a ch341 usb adapter (1a86:5512 QinHeng Electronics CH341 in EPP/MEM/I2C mode, EPP/I2C adapter).
When I run your program all the information are wrong (ff).
The program gave me the error "No CFI structure found, trying to get capacity from device ID. Set manually if detection fails."
If I set manually the length in bytes (2048) the result don't change.
What I have to make to solve?

The eeprom is a pc2400 (24c02),
Thank you and compliments for your program,
cheers,
Paolo

**Comment by setarcos** [comment]
Hi, Paolo
My program only deal with SPI protocol. For 24c02, you may resort to eepromtool from "http://sourceforge.net/projects/ch341eepromtool/"
Cheers,

**Comment by dronov** [comment]
@setarcos close this issue too, please. :)
